dist: trusty
language: java
jdk:
- oraclejdk8
- openjdk11
- openjdk12

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
  - secure: T0CAZe5S8BJTDWI5JiUYSsiuTJklQd1dyITpXbkrtas91CkC5v3/5B3MsY3TREGLG0mlPn/l1QitEndVbuj/JKdr5ezAllEHYXAQiOo40e40Gv1SVRR1vHn7EwMr6vCr0K027jSxsjBfVKKJqtcO4aZkAdDVfYBM1lanFlhSzf9ETRzN/uzbOaCqZOmouYd4oB4n+LWDjWVsrKRxwWq0ynuc6I2X6L8BhcTbVBmbXUidwIwCLYbXl2jCzyCm0DvZFCSi/fqjbPg9Asz/4dJwSge3bBw1803CB+B/SUE81EmKv0s51WKPBlDXncN215doNNcGPD1rLFwom2u/KyB7o9Si5pOqKLMRxRmnKJoMg6XWI/DpHJpZBH1O6dpAbI2xBty/uUyf5ODXyU31Ygh+y8RZQ5PEl9nLzMdQFufoJUbFVC3tox5OIXkFGkXAlvAmQhrk1e/D2n8nwN7RgTZP1Wd8Kgr+/sYeyr+bv9W/u839CJWy+/6AjIsKEn/GkiMOSFieilDfFmhxqzavD6N5BwqfgmkuGewaCR+m/xC9ghxc9s0X4mS8IHIT1Yv/ZOSKn5tSdPKTMGfWwv0XBPIggMGiEJG6xHw6juY9CwonTS7HSkQ74Cbb55HyrXCfXSK7V+fvPNHOJF1F3eqQMFZlTyi+wUJ3EsQtNHU7fhVIu9I=
  - secure: mm0au3zJs276pLkPHX40/rTWLo4ztUOJscSIek/yMrE3TKjhHIF144emzaa87xRBvTAphebcJLIkUHuWJEQMxTLQgMSfugmiKYqsPUQraaPVGkeYFKImBgspGbgP/il9gndrOOq2pU47SwwPElvuP+7/0iH10CSwOrNqCa2nnYDgJtwu/Ni+sCYkCOwczbaUSbBwJ0SzflbAJ5yHInwVNIh7eQsYsnauLudLPAWoZXQIiXUUNGOdvGkl1GVYYutRmX9AYZFHM/KTj+lXwPRVqBubqCn/uKAj8BCSaw9My8C2EpYIwbPoSalXjroUBNSQGYU/Z36KOqvJNWwxl4Bo48Y37vMVtKlB0H/o+fN5H88tz8utQQdobRB4eenB15cNZPGZ6E3KWvyu4j0Z8Byod/rQ3tjS7+Ku2S/GG/XnWhndFrV51Uba0Iu1yQzNei5hGUDtevi6Crnq9Znv105gALxJnHfE9aWPLae13NMcfoHZkzQ+e2DM4bvEa2d+OjGayjHuu648pCeA00M5JR4YiX5R1JyKEBzJ+HY27NvegmXuKaqQlztNKRgp/RPluDE1zRrOYissKTMYMTVwNc9ryufNBZWTYGKbIqMj//wnJsAA2ns8jnYGQh/t7TWoSYFFy602Teu5liAhqvl3grW/OAgtRMET+q5Eru7pFAxaVgg=

install: true

before_script:
- cp .travis/maven.settings.xml ~/.m2/settings.xml

script:
- mvn clean deploy --update-snapshots
